In [ ]:
"""
Problem Statement: To learn how to use NumPy for creating arrays,
performing basic array operations, and conducting numerical computations
through analyzing temperature data.
Scenario: You are given a list of daily average temperatures (in degrees Celsius)
recorded over two weeks. Your task is to use NumPy to analyze this data.
"""

In [7]:
import numpy as np

#Create a 1D NumPy array named temperatures_w1 for Week 1 with the following values:


temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
#Inspect the shape, data type, and the number of elements in the array.
#Inspect the shape of the temperatures_w1 array.

print(temperatures_w1.shape) #row,col
print(temperatures_w1.dtype)
print(temperatures_w1.size)

(7,)
float64
7


In [8]:
#Convert the temperatures_w1 from Celsius to Fahrenheit using the
#formula: Fahrenheit = (Celsius * 9/5) + 32

temperatures_f=(temperatures_w1*9/5)+32
print(temperatures_f)

#Find the maximum, minimum, and mean temperatures for the week.

max_temp=temperatures_f.max()
min_temp=temperatures_f.min()
mean_temp=temperatures_f.mean()
print("Maximum temprature is: ",max_temp)
print("Minumim temperature is :",min_temp)
print("Mean of temperatureis:",mean_temp)






[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum temprature is:  78.98
Minumim temperature is : 69.44
Mean of temperatureis: 74.37714285714286


In [9]:
"""
● Extract the temperatures for the first three days of the week.
● Extract the temperatures for the weekend (last two days).
● Extract the temperatures for the middle three days of the week.
"""
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)


print(temperatures_w1[:3])

print(temperatures_w1[-2:])

print(temperatures_w1[2:5])

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[22.5 25.3 20.8]
[24.8 21.9]
[20.8 23.4 26.1]


In [10]:
#Create a 2D NumPy array named temperatures where each row represents temperatures for a different week:

temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [13]:
""" Inspect and print the shape, data type, and total number of elements in the
temperatures array.
● Extract the temperatures for each week and the weekends (last two days)
for both weeks """

print(temperatures.shape)
print(temperatures.dtype)
print(temperatures.size)

print(temperatures[0][-2:])
print(temperatures[1][-2:])
#



(2, 7)
float64
14
[24.8 21.9]
[22.8 20.1]


In [21]:
import pandas as pd

#Create a Pandas Series named marks with the following data:

marks=pd.Series([95, 92, 89, 85, 80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [22]:
#Use the integer index position to access the mark of the 1st rank student.

print(marks[0])

95


/tmp/ipykernel_2772/3154738951.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [23]:
#Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels

top3_marks=marks.loc[['Rank1', 'Rank2', 'Rank3']]
print(top3_marks)

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [24]:
#Use the iloc accessor to retrieve the mark of the 3rd rank student

third_mark=marks.iloc[2]
print(third_mark)



89


In [25]:
#Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90

high_marks=marks[marks>90]
print(high_marks)

Rank1    95
Rank2    92
dtype: int64


In [27]:
#Modify the mark of the student with the 1st rank to 100.


marks.loc['Rank1']=100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [28]:
#Remove the entry corresponding to the last rank from the Series.

marks=marks.drop('Rank5')
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [29]:
#Compute the CGPA by dividing each mark in the Series by 10.
marks=marks/10
print(marks)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [34]:
transactions=pd.DataFrame({'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109,110],'ProductCategory':['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],'Region':['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West','South','North'],'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [40]:
#Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.

print(transactions.head())
print(transactions.tail())
print(transactions.shape)
print(transactions.columns)
print(transactions.dtypes)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
(10, 4)
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [42]:
#Display only the 'ProductCategory' and 'Amount' columns

print(transactions[['ProductCategory','Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [49]:
#Retrieve the last 3 columns of the DataFrame using iloc or loc.

print(transactions.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [50]:
#Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

north_transactions=transactions[(transactions['Region']=='North') & (transactions['Amount']>200)]
print(north_transactions)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [51]:
#Find the value counts for the 'ProductCategory' column

product_counts=transactions['ProductCategory'].value_counts()
print(product_counts)

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [52]:
#Find the unique values in the 'Region' column

unique_regions=transactions['Region'].unique()
print(unique_regions)

['North' 'South' 'East' 'West']


In [53]:
#Group by 'Region' and find the mean amount for each region.

region_means=transactions.groupby('Region')['Amount'].mean()
print(region_means)

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [61]:
#Modify the 'Amount' for the transaction with TransactionID 102 to 165

transactions.loc[transactions['TransactionID']==102,'Amount']=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [62]:
#Add a new column 'Discount' by calculating 10% of the 'Amount'

transactions['Discount']=transactions['Amount']*0.1
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [64]:
#Remove the row with TransactionID 109.

transactions=transactions.drop(transactions[transactions['TransactionID']==109].index)
print(transactions)



   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [65]:
#Delete the 'Discount' column from the DataFrame.

transactions=transactions.drop('Discount',axis=1)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
